# Auto-generated Terraform — test-vm (Azure)
# Generated by AI Infrastructure Agent

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    
  }

  backend "azurerm" {
    resource_group_name  = "test-vm-tfstate-rg"
    storage_account_name = "testvmtfstate"
    container_name       = "tfstate"
    key                  = "test-vm.terraform.tfstate"
  }
}

provider "azurerm" {
  features {}
}



resource "azurerm_resource_group" "main" {
  name     = "test-vm-rg"
  location = "centralindia"
  tags = {
    Project   = "test-vm"
    ManagedBy = "terraform"
  }
}




# ── Virtual Machine ─────────────────────────────────────────────────
resource "azurerm_public_ip" "app" {
  name                = "test-vm-pip"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_network_interface" "app" {
  name                = "test-vm-nic"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  ip_configuration {
    name                          = "internal"
    
    subnet_id                     = null # add a VNet/subnet if this VM needs networking
    
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.app.id
  }
}

resource "tls_private_key" "app_ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "azurerm_linux_virtual_machine" "app" {
  name                = "test-vm-vm"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  size                = "Standard_B1s"
  admin_username      = "azureuser"

  network_interface_ids = [azurerm_network_interface.app.id]

  admin_ssh_key {
    username   = "azureuser"
    public_key = tls_private_key.app_ssh.public_key_openssh
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts"
    version   = "latest"
  }

  tags = { Project = "test-vm" }
}

output "vm_ssh_private_key" {
  value       = tls_private_key.app_ssh.private_key_pem
  description = "Private key to SSH into the VM — retrieve with: terraform output -raw vm_ssh_private_key > key.pem"
  sensitive   = true
}

output "vm_public_ip" {
  value       = azurerm_public_ip.app.ip_address
  description = "Public IP of the virtual machine"
}












